version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      # Add environment variables here if required
      # Example:
      # APP_ENV: production
    restart: always
